### PR TITLE
Added hotkey to toggle Petra (works globally on City Page)

### PR DESCRIPTION
**Pull request by MusicManiac**
Will work regardless of which Tile is selected as long as player is in City Page, aka won't work in Research/World/etc.

### CODE REVIEW

**Comment by insraq** [comment]
This implementation has the following issue:
- the shortcut system does not have "global scope" by design as it will cause shortcut conflict.
- the shortcut is added to "global scope" but it is registered on TilePage, which is not global (although it covers maybe 80% of the UI views)
- the convention in this game is to always have a UI button accompanying the shortcut. Because the game will be released on other platforms that does not have keyboard.
- It's better to leave the save file as is. Storing "lastPetraSpeedUp" in the save file should be avoided. Instead it can be stored in the memory. Most similar settings in the game are stored in the memory and not persistented.

**Comment by MusicManiac** [comment]
> * the shortcut system does not have "global scope" by design as it will cause shortcut conflict.

There is no conflict between having 1 button be binded to 2 things, both callbacks still executed. If you are mean that you don't want to have same key be binded to 1 button, I don't see why not. The user can choose if they want to have 1 key do multiple things or 1. Why force keybind preferences on the player if the code supports a single bind to multiple functions?
> * the shortcut is added to "global scope" but it is registered on TilePage, which is not global (although it covers maybe 80% of the UI views)

I have been looking through a way to make keybind to work specifically on the city view, and this is the best solution I found. You said it covers 80%, can you point what does it not cover so I can look into it? Current alternative to TilePage is having same function being added to like 6 different places which is just bad.
> * the convention in this game is to always have a UI button accompanying the shortcut. Because the game will be released on other platforms that does not have keyboard.

You can't have a button that's intended to work in any place on city map unless you want to have button just floating around on your screen. It's simply impossible to have this type of shortcut to be present in non-keyboard environment. And as for convention I'd rather have QoL feature that works on systems with keyboard than have no QoL at all.
> * It's better to leave the save file as is. Storing "lastPetraSpeedUp" in the save file should be avoided. Instead it can be stored in the memory. Most similar settings in the game are stored in the memory and not persistented.

Wouldn't that make it so you have to set wanted warp every time you relaunch the game?

**Comment by insraq** [comment]
If you want to make a "global" control for Petra speed, its generally better to add the control to the resource panel, which presents globally. But given the panel is already very crowded, not sure if there's enough room for that.

**Comment by MusicManiac** [comment]
> > Why force keybind preferences on the player if the code supports a single bind to multiple functions?
> 
> Just because it happens to work doesn't means it's a desired behavior. I don't think softwares in general allow one shortcut binded to two different actions. 

There are plenty of games that allow multiple actions binded to same shortcut. At this point it is a standard in games. 

> And in the UI where you set shortcut, the game will check for conflicting shortcut. 

And where exacly does it do that and what does it do if there's same shortcut? Shortcut.ts has no code regarding that? Or am I looking in the wrong file? I can freely set Petra to B and Build last building on B and both functions fire when the keybind is pressed?  

> Global shortcut had another downside: you could be typing something and accidentally triggers the shortcut - that's why global shortcut is troublesome and generally avoided.

It does not trigger when you are typing in chat boxes. Also, same thing is already present in base game, I myself multiple times accidentally demolished a building with a keybind because I thought I was typing in chat but in reality I missed the chat window and just accidentally hit a "Demolish Buidling" keybind. I don't see how this is any different, except that this keybind has considerably less consequences for activating it accidentally.

**Comment by insraq** [comment]
> where exacly does it do that and what does it do if there's same shortcut?
EditShortcutModal.tsx

> here are plenty of games that allow multiple actions binded to same shortcut. At this point it is a standard in games. I haven't played a single game released in last 5 years that didn't allow multi-binds
I am not sure if I agree with this. I find it hard to believe a game would allow you to bind the same key to two actions at the same time. Regardless, I think this is a terrible UX.

> I don't see how this is any different, except that this keybind has considerably less consequences for activating it accidentally.
Having page-specific shortcut already causes these problems. Having a global shortcut will only make it worse.

I think if you want to move forward with this PR, we'd need to figure out an alternative design. The current implementation "as is" simply breaks too much current convention.

**Comment by MusicManiac** [comment]
> > where exacly does it do that and what does it do if there's same shortcut?
> 
> EditShortcutModal.tsx

It prevents having same shortcut in the same scope. You said multiple times that it cause problems but can you actually produce a single bug or incorrect behavior?

> > here are plenty of games that allow multiple actions binded to same shortcut. At this point it is a standard in games. I haven't played a single game released in last 5 years that didn't allow multi-binds
> 
> I am not sure if I agree with this. I find it hard to believe a game would allow you to bind the same key to two actions at the same time. Regardless, I think this is a terrible UX.

Brother, play some games, strategy games have been doing it from 2000s. And once again you are forcing *YOUR* preferences on people instead of letting them do what they prefer. 

> > I don't see how this is any different, except that this keybind has considerably less consequences for activating it accidentally.
> 
> Having page-specific shortcut already causes these problems. Having a global shortcut will only make it worse.

Such as? You keep declaring these vague "this is a problem" but can you provide an actual user-based scenario where it'd cause problem?

> I think if you want to move forward with this PR, we'd need to figure out an alternative design. The current implementation "as is" simply breaks too much current convention.

You have like 15 shortcuts, it's not a "shortcuts convention", it's a bare minimum to include "keyboard" in gaming process. 

Alternative design is putting same function in 8 different views and copy pasting same shortcut 8 times in shortcut options, once for each different scope. Which is pretty much a crime. 

You look at this from a perspective from a coder, I look at this from perspective of a user. I can guarantee to you if you fire up a poll if global Petra hotkey while you're in city view would be welcome you'll get all positive/neutral responses because people will either 
a) like it and want to use it
b) don't care for it and simply keep it unset.

If you want I can redo the commit to include same code in 8 different places of the project but it's a programming crime when there's much more elegant solution of including it in the parent page.

It's either 8 shortcuts in different scopes or 1 shortcut that covers all of the city scopes. Unless you have an alternative idea how to make city-global hotkey in line with you "conventions"

**Comment by insraq** [comment]
> Brother, play some games, strategy games have been doing it from 2000s. And once again you are forcing YOUR preferences on people instead of letting them do what they prefer.

I'd like to remind you that discussions here should be kept professional and on topic.

If you can provide examples of games that allow you to "bind one hotkey to multiple actions" so that if you press one key and two separate actions will trigger, I am happy to learn from them.

I am not suggesting having 8 shortcuts in different scopes, I agree that would be horrible. And I am sure a global Petra hotkey would be useful. In fact, I am sure any additional global hotkeys would be appreciated. But as I said, global hotkeys adds a new surface for mistakes and adds additional maintenance burden. As I have limited time working on this game, I am very reluctant to add features that would require more maintenance. **Because adding a certain feature is easy, maintaining it in the long run is hard.**

**Comment by MusicManiac** [comment]
> I think if you want to move forward with this PR, we'd need to figure out an alternative design.

Any ideas?

**Pull request closed without merging**
