### PR TITLE
Grand Bazaar Wonder

### PR DESCRIPTION
**Pull request by jimmyh77**
Obviously building does not have a graphic, I will leave that up to you.
It highlights the adjacent tiles when selected.
Gives the bonus from Great Lighthouse.
Currently only requires wood to build, I will leave that up to you.
Currently unlocked by Education, so you will probably want to move it.

I have not touched the Great Lighthouse.

I'm quite happy with it, but let me know if you want any changes or you have performance concerns and I can take a look.

### CODE REVIEW

**Comment by Krydax** [comment]
No idea the efficacy of your code, but I like the idea of market controlling!

**Comment by insraq** [comment]
Forgot to mention, can you change this PR to merge into `0.3` branch instead of main?

**Comment by jimmyh77** [comment]
> Forgot to mention, can you change this PR to merge into `0.3` branch instead of `main`?

Is this ok to do?
image

**Comment by insraq** [comment]
Sorry, misclicked the merge button. I was supposed to click comment

**Comment by insraq** [comment]
I suppose you need to open a new PR. Sorry about that

**Comment by jimmyh77** [comment]
No worries.  Can set it up with the right branch now.

**Pull request merged**
