### PR TITLE
Improve german translation

### PR DESCRIPTION
**Pull request by xyzzycgn**
- unified usage of salutation 
- some additional translations and corrections

### CODE REVIEW

**Comment by xyzzycgn** [comment]
I am a little bit puzzled - can't see the change which is complained by biome. What's going wrong?

**Comment by jimmyh77** [comment]
> I am a little bit puzzled - can't see the change which is complained by biome. What's going wrong?

It's telling you that the text for `OxfordUniversityDescV2` needs to be on a new line and indented.

**Comment by xyzzycgn** [comment]
Ok . Changed that - but why is there suddenly a need for an additional line break and indention - is it a margin that I violated?

**Comment by jimmyh77** [comment]
The settings for biome has a max line character count of 110, so when a line has more than that it's telling you to move to a new line.

**Comment by xyzzycgn** [comment]
thx for the quick responses and clarification

**Comment by insraq** [comment]
Don't worry about Biome, I can fix it later

**Pull request merged**
