### PR TITLE
Revert "Update PlayerTradeComponent.tsx"

### PR DESCRIPTION
**Pull request by insraq**
Reverts fishpondstudio/CivIdle#3

### CODE REVIEW

**Comment by insraq** [comment]
image

Revert due to performance issue

**Comment by jimmyh77** [comment]
@insraq Any idea as to the cause?

**Comment by insraq** [comment]
I spend like 30mins taking a brief look but as you can see from the screenshot of the profiler data, it does not point to any specific function. I think it might be related to the way filters are implemented - I am not a React expert so I cannot spot the issue immediately.

**Comment by jimmyh77** [comment]
> I spend like 30mins taking a brief look but as you can see from the screenshot of the profiler data, it does not point to any specific function. I think it might be related to the way filters are implemented - I am not a React expert so I cannot spot the issue immediately.

Hmmm, I'm not seeing the same issue.  Do you have lots of trades?   I only have a few resources in my map, so it could be that.

image

**Pull request merged**
